[config]
schemaVersion = "0.0.1"

[package]
namespace = "GravitonGamer"
name = "Monster_Train_2_Relics_Reloaded"
versionNumber = "1.3.1"
description = "Brings back several of the relics from the original Monster Train to Monster Train 2."
websiteUrl = "https://github.com/Jace17/MT2RelicsReloaded"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
MT2-Trainworks_Reloaded = "0.6.9"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./"

[[build.copy]]
source = "./plugin_build"
target = ""

[publish]
repository = "https://thunderstore.io"
communities = [ "monster-train-2" ]


